[package]
name = "ion"
version = "0.1.0"
edition = "2024"

[lib]

[lints]
workspace = true

[dependencies]
flume.workspace = true
futures.workspace = true
v8.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
normalize-path.workspace = true
async_fn_traits = "0.1.1"
num_cpus.workspace = true
parking_lot.workspace = true
rand = "0.9.2"
